### ISSUE TITLE
`benchmark_result_df` is broken

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/BLASBenchmarksCPU.jl#34]
https://github.com/chriselrod/BLASBenchmarksCPU.jl/pull/32 broke the public function `benchmark_result_df(::BenchmarkResult)` because the `BenchmarkResult` struct no longer has a `df` field.

So we need a new public API that allows users to extract the data from a `BenchmarkResult` so that they can pass it to the plotting library of their choosing.

Also, we should make sure that for this new public API, we add some tests for it. I forgot to add tests for `benchmark_result_df`, which is why we didn't notice that we broke it 😂

**Comment by chriselrod** [comment]
The show method still creates a dataframe, because `Gadfly` depends on `DataFrame`s, I didn't see the need to drop that dependency ourselves.
While it'd be nice eventually to use PrettyTables to highlight the column with the best GFLOPS in each row, data frames look a lot better than dumping a matrix...

This dataframe is organized differently, but we could `stack` it. Do you have specific requirements on the dataframe's contents and layout?

**Comment by chriselrod** [comment]
Fixed?
